"""Patch script: update MP surface hit section in tracer.py to add BSDF dispatch."""
import re

content = open('backlight_sim/sim/tracer.py', 'r', encoding='utf-8').read()

old = (
    "        # Surface hits (simplified — no path recording in MP mode)\n"
    "        surf_hit_mask = (best_type == 0) & ~missed\n"
    "        if surf_hit_mask.any():\n"
    "            for si, surf in enumerate(surfaces):\n"
    "                smask = surf_hit_mask & (best_obj == si)\n"
    "                if not smask.any():\n"
    "                    continue\n"
    "                hit_idx = active_idx[smask]\n"
    "                t_vals = best_t[smask]\n"
    "                hit_pts = origins[hit_idx] + t_vals[:, None] * directions[hit_idx]\n"
    "                normal = surf.normal\n"
    "                mat = materials.get(surf.material_name)\n"
    "                if mat is None or mat.surface_type == \"absorber\":\n"
    "                    alive[hit_idx] = False\n"
    "                    continue\n"
    "                dot = np.einsum(\"ij,j->i\", directions[hit_idx], normal)\n"
    "                flip = dot > 0\n"
    "                on = np.where(flip[:, None], -normal, normal)\n"
    "                if mat.surface_type == \"reflector\":\n"
    "                    weights[hit_idx] *= mat.reflectance\n"
    "                    new_dirs = _reflect_batch(directions[hit_idx], on, mat.is_diffuse, rng)\n"
    "                    if mat.haze > 0 and not mat.is_diffuse:\n"
    "                        new_dirs = scatter_haze(new_dirs, mat.haze, rng)\n"
    "                    origins[hit_idx] = hit_pts + on * _EPSILON\n"
    "                    directions[hit_idx] = new_dirs\n"
    "                elif mat.surface_type == \"diffuser\":\n"
    "                    n_rays = len(hit_idx)\n"
    "                    roll = rng.uniform(size=n_rays)\n"
    "                    transmits = roll < mat.transmittance\n"
    "                    if transmits.any():\n"
    "                        ti = hit_idx[transmits]\n"
    "                        through_n = -on[transmits]\n"
    "                        new_d = sample_lambertian(int(transmits.sum()), through_n[0], rng)\n"
    "                        origins[ti] = hit_pts[transmits] + through_n * _EPSILON\n"
    "                        directions[ti] = new_d\n"
    "                    reflects = ~transmits\n"
    "                    if reflects.any():\n"
    "                        ri = hit_idx[reflects]\n"
    "                        weights[ri] *= mat.reflectance\n"
    "                        refl_on = on[reflects]\n"
    "                        new_d = _reflect_batch(directions[ri], refl_on, mat.is_diffuse, rng)\n"
    "                        origins[ri] = hit_pts[reflects] + refl_on * _EPSILON\n"
    "                        directions[ri] = new_d"
)

new = (
    "        # Surface hits (simplified — no path recording in MP mode)\n"
    "        surf_hit_mask = (best_type == 0) & ~missed\n"
    "        if surf_hit_mask.any():\n"
    "            for si, surf in enumerate(surfaces):\n"
    "                smask = surf_hit_mask & (best_obj == si)\n"
    "                if not smask.any():\n"
    "                    continue\n"
    "                hit_idx = active_idx[smask]\n"
    "                t_vals = best_t[smask]\n"
    "                hit_pts = origins[hit_idx] + t_vals[:, None] * directions[hit_idx]\n"
    "                normal = surf.normal\n"
    "                # Resolve optical properties (optical_properties_name takes priority)\n"
    "                mat = None\n"
    "                if getattr(surf, 'optical_properties_name', ''):\n"
    "                    mat = project.optical_properties.get(surf.optical_properties_name)\n"
    "                if mat is None:\n"
    "                    mat = materials.get(surf.material_name)\n"
    "                if mat is None or mat.surface_type == \"absorber\":\n"
    "                    alive[hit_idx] = False\n"
    "                    continue\n"
    "                dot = np.einsum(\"ij,j->i\", directions[hit_idx], normal)\n"
    "                flip = dot > 0\n"
    "                on = np.where(flip[:, None], -normal, normal)\n"
    "                # BSDF dispatch\n"
    "                bsdf_name_mp = getattr(mat, 'bsdf_profile_name', '')\n"
    "                if bsdf_name_mp and bsdf_cdf_cache_mp.get(bsdf_name_mp) is not None:\n"
    "                    bsdf_prof_mp = (getattr(project, 'bsdf_profiles', {}) or {}).get(bsdf_name_mp, {})\n"
    "                    cdfs_mp = bsdf_cdf_cache_mp[bsdf_name_mp]\n"
    "                    theta_in_vals_mp = cdfs_mp['theta_in']\n"
    "                    refl_total_mp = cdfs_mp['refl_total']\n"
    "                    trans_total_mp = cdfs_mp['trans_total']\n"
    "                    cos_i_mp = np.clip(np.einsum('ij,j->i', -directions[hit_idx], on[0]), 0.0, 1.0)\n"
    "                    theta_i_deg_mp = np.degrees(np.arccos(cos_i_mp))\n"
    "                    bin_idx_mp = np.clip(\n"
    "                        np.searchsorted(theta_in_vals_mp, theta_i_deg_mp, side='right') - 1,\n"
    "                        0, len(theta_in_vals_mp) - 1\n"
    "                    )\n"
    "                    r_total_mp = refl_total_mp[bin_idx_mp]\n"
    "                    t_total_mp = trans_total_mp[bin_idx_mp]\n"
    "                    rt_sum_mp = r_total_mp + t_total_mp\n"
    "                    absorption_frac_mp = np.where(rt_sum_mp > 0, 1.0 - np.minimum(rt_sum_mp, 1.0), 1.0)\n"
    "                    weights[hit_idx] *= (1.0 - absorption_frac_mp)\n"
    "                    roll_mp = rng.random(len(hit_idx))\n"
    "                    p_refl_mp = np.where(rt_sum_mp > 0, r_total_mp / np.maximum(rt_sum_mp, 1e-12), 1.0)\n"
    "                    refl_bsdf_mp = roll_mp < p_refl_mp\n"
    "                    trans_bsdf_mp = ~refl_bsdf_mp\n"
    "                    if refl_bsdf_mp.any():\n"
    "                        ri = hit_idx[refl_bsdf_mp]\n"
    "                        on_r = on[refl_bsdf_mp]\n"
    "                        surf_n_mp = on_r[0] if len(on_r) > 0 else normal\n"
    "                        new_dirs = sample_bsdf(int(refl_bsdf_mp.sum()), directions[ri], surf_n_mp, bsdf_prof_mp, 'reflect', rng, cdfs=cdfs_mp)\n"
    "                        origins[ri] = hit_pts[refl_bsdf_mp] + on_r * _EPSILON\n"
    "                        directions[ri] = new_dirs\n"
    "                    if trans_bsdf_mp.any():\n"
    "                        ti2 = hit_idx[trans_bsdf_mp]\n"
    "                        on_t = on[trans_bsdf_mp]\n"
    "                        surf_n_mp = on_t[0] if len(on_t) > 0 else normal\n"
    "                        new_dirs = sample_bsdf(int(trans_bsdf_mp.sum()), directions[ti2], surf_n_mp, bsdf_prof_mp, 'transmit', rng, cdfs=cdfs_mp)\n"
    "                        through_n = -on_t\n"
    "                        origins[ti2] = hit_pts[trans_bsdf_mp] + through_n * _EPSILON\n"
    "                        directions[ti2] = new_dirs\n"
    "                    continue\n"
    "                if mat.surface_type == \"reflector\":\n"
    "                    weights[hit_idx] *= mat.reflectance\n"
    "                    new_dirs = _reflect_batch(directions[hit_idx], on, mat.is_diffuse, rng)\n"
    "                    if mat.haze > 0 and not mat.is_diffuse:\n"
    "                        new_dirs = scatter_haze(new_dirs, mat.haze, rng)\n"
    "                    origins[hit_idx] = hit_pts + on * _EPSILON\n"
    "                    directions[hit_idx] = new_dirs\n"
    "                elif mat.surface_type == \"diffuser\":\n"
    "                    n_rays = len(hit_idx)\n"
    "                    roll = rng.uniform(size=n_rays)\n"
    "                    transmits = roll < mat.transmittance\n"
    "                    if transmits.any():\n"
    "                        ti = hit_idx[transmits]\n"
    "                        through_n = -on[transmits]\n"
    "                        new_d = sample_lambertian(int(transmits.sum()), through_n[0], rng)\n"
    "                        origins[ti] = hit_pts[transmits] + through_n * _EPSILON\n"
    "                        directions[ti] = new_d\n"
    "                    reflects = ~transmits\n"
    "                    if reflects.any():\n"
    "                        ri = hit_idx[reflects]\n"
    "                        weights[ri] *= mat.reflectance\n"
    "                        refl_on = on[reflects]\n"
    "                        new_d = _reflect_batch(directions[ri], refl_on, mat.is_diffuse, rng)\n"
    "                        origins[ri] = hit_pts[reflects] + refl_on * _EPSILON\n"
    "                        directions[ri] = new_d"
)

if old in content:
    content = content.replace(old, new, 1)
    open('backlight_sim/sim/tracer.py', 'w', encoding='utf-8').write(content)
    print('MP SURFACE BSDF UPDATED')
else:
    print('NOT FOUND - looking for pattern...')
    idx = content.find('# Surface hits (simplified')
    if idx >= 0:
        print(repr(content[idx:idx+500]))
    else:
        print('No surface hits section found')
